#!/usr/bin/env bash

if [ -f composer.json ]; then
    composer install --prefer-dist
fi

if [ -n "$APP_KEY" ]; then
    APP_KEY=$(php artisan key:generate --show)
    export APP_KEY
fi

if [ -f package.json ]; then
  if [ ! -d ~/.nvm ]; then
      nvm-install
  fi

  if [ -z "$NVM_DIR" ]; then
     export NVM_DIR="$HOME/.nvm"
     [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
     [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
  fi

  nvm install "${NODE_VERSION:-18}"
  nvm use "${NODE_VERSIOM:-18}"

  npm ci
  if [ -f vite.config.js ]; then
      npm run build
  elif [ -f webpack.mix.js ]; then
      npm run prod
  fi
fi


alias test="php artisan test"
export PATH="$PATH:/var/www/html/vendor/bin/"
