#!/usr/bin/env bash

if [ -z "$NVM_DIR" ]; then
  if [ ! -d "$HOME/.nvm/" ]; then
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
  fi
  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
  [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
fi

NODE_VERSION="${NODE_VERSION:-18}"

if [[ $(nvm ls | grep "$NODE_VERSION") == "" ]]; then
  nvm install "$NODE_VERSION"
fi
nvm use "$NODE_VERSION"