#!/usr/bin/env bash

. build-env -k

if [ -z "$APP_KEY" ]; then
  echo "APP_KEY not set";
  exit 1;
elif [ "$APP_KEY" != "artisan" ]; then
  echo "'$APP_KEY' does not match expected value 'artisan'";
  exit 1;
fi
