#!/usr/bin/env bash

if [ "${DB_HOST}" = "localhost" ]; then
    echo "DROP DATABASE IF EXISTS ${DB_DATABASE};" | mysql -uroot -ppassword
    echo "CREATE DATABASE ${DB_DATABASE};" | mysql -uroot -ppassword
    echo "CREATE USER '${DB_USERNAME}'@'${DB_HOST}' IDENTIFIED BY '${DB_PASSWORD}'" | mysql -uroot -ppassword
    echo "GRANT ALL PRIVILEGES ON '${DB_DATABASE}'.* TO '${DB_USERNAME}'@'${DB_HOST}' WITH GRANT OPTION;" | mysql -uroot -ppassword
    echo "FLUSH PRIVILEGES;" | mysql -uroot -ppassword
fi

if [ -f composer.json ]; then
    composer install --prefer-dist
fi

if [ -n "$APP_KEY" ]; then
    APP_KEY=$(php artisan key:generate --show)
    export APP_KEY
fi

if [ -f package.json ]; then
  npm ci
fi

if [ -f vite.config.js ]; then
    npm run build
elif [ -f webpack.mix.js ]; then
    npm run prod
fi

alias test="php artisan test"
export PATH="$PATH:/var/www/html/vendor/bin/"