#!/usr/bin/env bash

INSTALL_COMPOSER=1
GENERATE_KEY=1
BUILD_ASSETS=0

USAGE="Usage: build-env [options]
OPTIONS:
 -c --skip-composer  Do not run composer install
 -k --skip-key       Do not attempt to set the app key if it is missing
 -a --assets         Install NPM and build assets
 -h --help           Display this help and exit"

while test $# != 0
do
    case "$1" in
    -h|--help) echo "$USAGE"; exit 1;;
    -k|--skip-key) INSTALL_COMPOSER=0 ;;
    -c|--skip-composer) GENERATE_KEY=0 ;;
    -a|--assets) BUILD_ASSETS=1 ;;
    esac
    shift
done

if [ $INSTALL_COMPOSER ]; then
  if [ -f composer.json ]; then
      composer install --prefer-dist
  fi
fi

if [ $GENERATE_KEY ]; then
  if [ -z "$APP_KEY" ]; then
    APP_KEY=$(php artisan key:generate --show);
    export APP_KEY;
  fi
fi

if [ $BUILD_ASSETS ]; then
  setup-node

  if [ -f package.json ]; then
    if [ -f package.lock ]; then
      npm ci
    else
      npm install
    fi

    if [ -f vite.config.js ]; then
        npm run build
    elif [ -f webpack.mix.js ]; then
        npm run prod
    fi
  fi
fi

alias test="php artisan test"
export PATH="$PATH:/var/www/html/vendor/bin/"
