#!/usr/bin/env bash

NODE_EXISTS=0
if [ -f package.json ]; then
    NODE_EXISTS=1
fi

NODE_INSTALLED=0
if [ $NODE_EXISTS ] && [ -d node_modules ]; then
    NODE_INSTALLED=1
fi

COMPOSER_INSTALLED=0
if [ -d vendor ]; then
  COMPOSER_INSTALLED=1
fi

INSTALL_COMPOSER=1
GENERATE_KEY=1
INSTALL_NODE=1
BUILD_ASSETS=0

if [ $NODE_EXISTS ] && [ $NODE_INSTALLED -eq 0 ]; then
    INSTALL_NODE=1
fi

if [ $COMPOSER_INSTALLED ]; then
    INSTALL_COMPOSER=0
fi

USAGE="Usage: build-env [options]
OPTIONS:
 -h Display this help and exit
 -c Do not run composer install
 -k Do not attempt to set the app key if it is missing
 -n Do set run npm install
 -a Build frontend assets"

while getopts 'hkcan' OPTION
do
    case "$OPTION" in
    h) echo "$USAGE"; exit 1;;
    c) INSTALL_COMPOSER=0 ;;
    k) GENERATE_KEY=0 ;;
    n) INSTALL_NODE=0 ;;
    a) BUILD_ASSETS=1 ;;
    *) ;;
    esac
done

if [ $INSTALL_COMPOSER ]; then
  if [ -f composer.json ]; then
      composer install --prefer-dist
  fi
fi

if [ $GENERATE_KEY ]; then
  if [ -z "$APP_KEY" ]; then
    APP_KEY=$(php artisan key:generate --show);
    export APP_KEY;
  fi
fi

if [ $INSTALL_NODE ]; then
  if [ -f package.lock ]; then
    npm ci
  else
    npm install
  fi
  NODE_INSTALLED=1
fi

if [ $BUILD_ASSETS ]; then
  if [ -f vite.config.js ]; then
      npm run build
  elif [ -f webpack.mix.js ]; then
      npm run prod
  fi
fi
