#!/usr/bin/env bash

set -e

RED="\e[31m"
GREEN="\e[32m"
CODE="\e[1;34;40m"
ENDCOLOR="\e[0m"

NODE_EXISTS=0
if [ -f package.json ]; then
    NODE_EXISTS=1
fi

NODE_INSTALLED=0
if [ $NODE_EXISTS -eq 1 ] && [ -d node_modules ]; then
    NODE_INSTALLED=1
fi

COMPOSER_INSTALLED=0
if [ -d vendor ]; then
  COMPOSER_INSTALLED=1
fi

INSTALL_COMPOSER=1
GENERATE_KEY=1
INSTALL_NODE=1
BUILD_ASSETS=0

if [ $COMPOSER_INSTALLED -eq 1 ]; then
    INSTALL_COMPOSER=0
fi

USAGE="Usage: build-env [options]
OPTIONS:
 -h Display this help and exit
 -c Do not run composer install
 -k Do not attempt to set the app key if it is missing
 -n Do not run npm install
 -a Build frontend assets"

while getopts 'hkcan' OPTION
do
    case "$OPTION" in
    h) echo "$USAGE"; exit 1;;
    c) INSTALL_COMPOSER=0 ;;
    k) GENERATE_KEY=0 ;;
    n) INSTALL_NODE=0 ;;
    a) BUILD_ASSETS=1 ;;
    *) ;;
    esac
done

if [ $INSTALL_COMPOSER -eq 1 ] && [ $COMPOSER_INSTALLED -eq 0 ]; then
  if [ -f composer.json ]; then
      echo -e "${GREEN}Installing composer${ENDCOLOR}"
      composer install --prefer-dist
  else
      echo -e "${RED}Cannot install composer${ENDCOLOR}: Cannot find \`${CODE}${PWD}/composer.json${ENDCOLOR}\`"
  fi
fi

if [ $GENERATE_KEY -eq 1 ]; then
  if [ -z "$APP_KEY" ]; then
    echo -e "Generating ${CODE}APP_KEY${ENDCOLOR} with \`${CODE}php artisan key:generate${ENDCOLOR}\`"
    APP_KEY=$(php artisan key:generate --show);
    export APP_KEY;
  fi
fi

if [ $INSTALL_NODE -eq 1 ] && [ $NODE_INSTALLED -eq 0 ]; then
  if [ $NODE_EXISTS -eq 0 ]; then
    echo -e "${RED}Cannot install npm${ENDCOLOR}: Cannot find \`${CODE}${PWD}/package.json${ENDCOLOR}\`"
  else
    if [ -f package.lock ]; then
      echo -e "${GREEN}Installing NPM modules${ENDCOLOR}: running \`${CODE}npm ci${ENDCOLOR}\`"
      npm ci
    else
      echo -e "${GREEN}Installing NPM modules${ENDCOLOR}: running \`${CODE}npm install${ENDCOLOR}\`"
      npm install
    fi
    NODE_INSTALLED=1
  fi
fi

if [ $BUILD_ASSETS -eq 1 ]; then
  if [ $NODE_INSTALLED -eq 1 ]; then
    if [ -f vite.config.js ]; then
        echo -e "${GREEN}Building assets with vite${ENDCOLOR}"
        npm run build
    elif [ -f webpack.mix.js ]; then
        echo -e "${GREEN}Building assets with mix${ENDCOLOR}"
        npm run prod
    else
      echo -e "${RED}Cannot build assets${ENDCOLOR}: Cannot find \`${CODE}${PWD}/vite.config.js${ENDCOLOR}\` or \`${CODE}${PWD}/webpack.mix.js${ENDCOLOR}\`"
    fi
  else
    echo -e "${RED}Cannot build assets${ENDCOLOR}: NPM modules are not installed"
  fi
fi
