#!/usr/bin/env bash

set -e

RED="\e[31m"
GREEN="\e[32m"
CODE="\e[1;34;40m"
ENDCOLOR="\e[0m"

NODE_EXISTS=0
if [ -f package.json ]; then
    NODE_EXISTS=1
fi

NODE_INSTALLED=0
if [ $NODE_EXISTS -eq 1 ] && [ -d node_modules ]; then
    NODE_INSTALLED=1
fi

COMPOSER_INSTALLED=0
if [ -d vendor ]; then
  COMPOSER_INSTALLED=1
fi

INSTALL_COMPOSER=0
GENERATE_KEY=0
INSTALL_NODE=0
BUILD_ASSETS=0

USAGE="Usage: build-env [options]
OPTIONS:
 -a Build frontend assets
 -h Display this help and exit
 -c Run composer install
 -k Set the app key if it is missing
 -n Run npm install"

while getopts 'hkcan' OPTION
do
    case "$OPTION" in
    h) echo "$USAGE"; exit 1;;
    c) INSTALL_COMPOSER=1 ;;
    k) GENERATE_KEY=1 ;;
    n) INSTALL_NODE=1 ;;
    a) BUILD_ASSETS=1 ;;
    *) ;;
    esac
done

if [ $INSTALL_COMPOSER -eq 1 ]; then
  if [ -f composer.json ]; then
      echo -e "${GREEN}Installing composer${ENDCOLOR}"
      composer install --prefer-dist
      COMPOSER_INSTALLED=1
  else
      echo -e "${RED}Cannot install composer${ENDCOLOR}: Cannot find \`${CODE}${PWD}/composer.json${ENDCOLOR}\`"
  fi
fi

if [ $GENERATE_KEY -eq 1 ]; then
  # No .env, but a .env.ci, so use the .env.ci
  if [[ ! -f .env ]] && [[ -f .env.ci ]]; then
    echo -e "Copying \`${CODE}.env.ci${ENDCOLOR}\` to \`${CODE}.env${ENDCOLOR}\`"
    cp .env.ci .env
  fi
  # No app key defined, but we have a .env - load it into the environment
  if [[ -z "$APP_KEY" ]] && [[ -f .env ]]; then
    echo -e "Loading environment from \`${CODE}.env${ENDCOLOR}\`"
    set -o allexport
    source .env
    set +o allexport
  fi
  # No app key set. Use artisan to generate one
  if [ -z "$APP_KEY" ]; then
    if [[ $COMPOSER_INSTALLED -eq 1 ]] && [[ -f artisan ]]; then
      echo -e "Generating ${CODE}APP_KEY${ENDCOLOR} with \`${CODE}php artisan key:generate${ENDCOLOR}\`"
      APP_KEY=$(php artisan key:generate --show);
      export APP_KEY;
    elif [ $COMPOSER_INSTALLED -eq 1 ]; then
      echo -e "${RED}Cannot set application key${ENDCOLOR}: \`${CODE}artisan${ENDCOLOR}\` does not exist"
    else
      echo -e "${RED}Cannot set application key${ENDCOLOR}: Composer not installed"
    fi
  fi
fi

if [ $INSTALL_NODE -eq 1 ]; then
  if [ $NODE_EXISTS -eq 0 ]; then
    echo -e "${RED}Cannot install npm${ENDCOLOR}: Cannot find \`${CODE}${PWD}/package.json${ENDCOLOR}\`"
  else
    if [[ -f package-lock.json ]] || [[ -f npm-shrinkwrap.json ]]; then
      echo -e "${GREEN}Installing NPM modules${ENDCOLOR}: running \`${CODE}npm ci${ENDCOLOR}\`"
      npm ci
    else
      echo -e "${GREEN}Installing NPM modules${ENDCOLOR}: running \`${CODE}npm install${ENDCOLOR}\`"
      npm install
    fi
    NODE_INSTALLED=1
  fi
fi

if [ $BUILD_ASSETS -eq 1 ]; then
  if [ $NODE_INSTALLED -eq 1 ]; then
    if [ -f vite.config.js ]; then
        echo -e "${GREEN}Building assets with vite${ENDCOLOR}"
        npm run build
    elif [ -f webpack.mix.js ]; then
        echo -e "${GREEN}Building assets with mix${ENDCOLOR}"
        npm run prod
    else
      echo -e "${RED}Cannot build assets${ENDCOLOR}: Cannot find \`${CODE}${PWD}/vite.config.js${ENDCOLOR}\` or \`${CODE}${PWD}/webpack.mix.js${ENDCOLOR}\`"
    fi
  else
    echo -e "${RED}Cannot build assets${ENDCOLOR}: NPM modules are not installed"
  fi
fi
