#!/usr/bin/env bash

if [ -d "/.composer/vendor/bin" ] ; then
    PATH="/.composer/vendor/bin:$PATH"
fi

if [ -d "$HOME/.config/composer/vendor/bin" ] ; then
    PATH="$HOME/.config/composer/vendor/bin:$PATH"
fi