#!/usr/bin/env bash

if [ -n "$WWWUSER" ]; then
    usermod -u $WWWUSER laravelci
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi
chmod -R ugo+rw /.composer

if [ -d "/.composer/vendor/bin" ] ; then
    PATH="/.composer/vendor/bin:$PATH"
fi

if [ -n "$SRC_PATH" ] && [ "$(realpath "$PWD")" != "$(realpath "$SRC_PATH")" ] && [ -d "$SRC_PATH" ]; then
    cd "$SRC_PATH" || exit 1
fi

if [ $# -gt 0 ]; then
    exec gosu laravelci "$@"
else
    exec gosu laravelci build-env -h
fi
