name: Builds testing container
on:
  workflow_call:

jobs:
  BuildBaseImage:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:base"
          file: Dockerfile
          tags: testbed-base:latest
          outputs: type=docker,dest=/tmp/testbed-base.tar
      -
        name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: testbed-base
          path: /tmp/testbed-base.tar
          overwrite: true
  BuildTestbed:
    strategy:
      matrix:
        php: ["8.2", "8.3"]
        node: [20]
        include:
          - php: "8.0"
            node: 16
          - php: "8.1"
            node: 18
    runs-on: ubuntu-latest
    needs: BuildBaseImage
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        uses: actions/download-artifact@v4
        with:
          name: testbed-base
          path: /tmp
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Load base container
        run: |
          docker load --input /tmp/testbed-base.tar
          docker image ls -a
      -
        name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:build"
          file: Dockerfile
          tags: testbed-php${{matrix.php}}:latest
          outputs: type=docker,dest=/tmp/testbed-${{matrix.php}}.tar
          build-args: |
            PHP_VERSION=${{matrix.php}}
            NODE_VERSION=${{matrix.node}}
            BASE_IMAGE=testbed-base:latest
      -
        name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: testbed-${{matrix.php}}
          path: /tmp/testbed-${{matrix.php}}.tar
          overwrite: true
