name: Builds testing container
on:
  workflow_call:

jobs:
  BuildTestbed:
    strategy:
      matrix:
        php: ["8.2", "8.3"]
        node: [20]
        include:
          - php: "8.0"
            node: 16
          - php: "8.1"
            node: 18
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and export
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:base"
          file: Dockerfile
          tags: testbed/php${{matrix.php}}:latest
          outputs: type=docker,dest=/tmp/testbed-${{matrix.php}}.tar
          args: |
            PHP_VERSION=${{matrix.php}}
            NODE_VERSION=${{matrix.node}}
      -
        name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: testbed-${{matrix.php}}
          path: /tmp/testbed-${{matrix.php}}.tar
