name: Deploy Docker PrerRse Images

on:
  release:
    types:
      - released
    branches:
      - main

jobs:
  BuildAndDeployImages:
    strategy:
      matrix:
        php: ['8.0', '8.1', '8.2', '8.3']
        node: [20]
        include:
          - php: 8.0
            node: 16
          - php: 8.1
            node: 18
    uses: ./.github/workflows/build-image.yml
    with:
      tags: |
        ddsam/laravel-ci:php${{matrix.php}}
        ddsam/laravel-ci:php${{matrix.php}}-${{github.ref_name}}
      args: |
        PHP_VERSION=${{matrix.php}}
        NODE_VERSION=${{matrix.node}}
    secrets: inherit

