name: Deploy Docker Release Images

on:
  release:
    types:
      - released
    branches:
      - main

jobs:
  BuildAndDeployBaseImage:
    uses: ./.github/workflows/build-base.yml
    with:
      tags: |
        ddsam/laravel-ci:base
        ddsam/laravel-ci:base-${{github.ref_name}}
  BuildAndDeployImages:
    needs: BuildAndDeployBaseImage
    strategy:
      matrix:
        php: ["8.2", "8.3"]
        node: [20]
        include:
          - php: "8.0"
            node: 16
          - php: "8.1"
            node: 18
    uses: ./.github/workflows/build-image.yml
    with:
      tags: |
        ddsam/laravel-ci:php${{matrix.php}}
        ddsam/laravel-ci:php${{matrix.php}}-${{github.ref_name}}
      args: |
        PHP_VERSION=${{matrix.php}}
        NODE_VERSION=${{matrix.node}}
        BASE_IMAGE=ddsam/laravel-ci:base-${{github.ref_name}}
    secrets: inherit

