name: Release Docker Images

on:
  release:
    types:
      - released
    branches:
      - main

jobs:
  build-80:
    uses: determined-development/laravel-ci/.github/workflows/build-image.yml@main
    with:
      image-name: 'php8.0'
      tags: 'ddsam/laravel-ci:php8.0'
    secrets: inherit
  build-81:
    uses: determined-development/laravel-ci/.github/workflows/build-image.yml@main
    with:
      image-name: 'php8.1'
      tags: 'ddsam/laravel-ci:php8.1'
    secrets: inherit
  build-82:
    uses: determined-development/laravel-ci/.github/workflows/build-image.yml@main
    with:
      image-name: 'php8.2'
      tags: 'ddsam/laravel-ci:php8.2,ddsam/laravel-ci:latest'
    secrets: inherit