name: Test containers
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main


jobs:
  BuildTestbed:
    uses: ./.github/workflows/build-testbed.yml
  TestCommand:
    runs-on: ubuntu-latest
    needs: BuildTestbed
    strategy:
      matrix:
        php: ["8.0", "8.1", "8.2", "8.3"]
        test: [composer, env, env-ci, global-composer]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: testbed-${{matrix.php}}
          path: /tmp
      - name: Test container
        run: |
          docker load --input /tmp/testbed-${{matrix.php}}.tar
          docker run --rm -t -v ${{ github.workspace }}/tests/${{matrix.test}}:/var/www/html --env WWWUSER=1001 --name testbed testbed-php${{matrix.php}} bash test
