name: Test containers
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main


jobs:
  BuildTestbed:
    uses: ./.github/workflows/build-testbed.yml
  TestCommand:
    runs-on: ubuntu-latest
    needs: BuildTestbed
    strategy:
      matrix:
        php: ["8.0", "8.1", "8.2", "8.3"]
        test: [composer, env, env-ci]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: actions/download-artifact@v4
        with:
          name: testbed-${{matrix.php}}
          path: /tmp
      - name: Test container
        run: |
          docker load --input /tmp/testbed-${{matrix.php}}.tar
          docker image ls
          docker create -t -v ${pwd}/tests/${{matrix.test}}:/var/www/html --name testbed testbed-php${{matrix.php}}:latest
          docker run -t testbed chmod a+x /var/www/html/test
          docker run -t testbed /var/www/html/test
          docker rm testbed
